// user login in...
export const ADD_USER_LOGIN = 'ADD_USER_LOGIN'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_FAIL = 'ADD_USER_FAIL'
export const ADD_USER_REQUIRES = 'ADD_USER_REQUIRES'


// user id 
export const ADD_USERID_FAIL = 'ADD_USERID_FAIL'
export const ADD_USERID_LOADING = 'ADD_USERID_LOADING'
export const ADD_USERID_SUCCESS = 'ADD_USERID_SUCCESS'

// change profile 
export const ADD_CHANGE_PROFILE_SUCCESS = 'ADD_CHANGE_PROFILE_SUCCESS'
export const ADD_CHANGE_PROFILE_FAIL = 'ADD_CHANGE_PROFILE_FAIL'
// views story. 
export const ADD_STORY_VIEWS_SUCCESS = 'ADD_STORY_VIEWS_SUCCESS'
export const ADD_STORY_VIEWS_FAIL = 'ADD_STORY_VIEWS_FAIL'

// user followare... 
export const ADD_USER_FOLLOWARE_LOADING =  'ADD_USER_FOLLOWARE_LOADING'
export const ADD_USER_FOLLOWARE_SUCCESS = 'ADD_USER_FOLLOWARE_SUCCESS'
export const ADD_USER_FOLLOWARE_FAIL = 'ADD_USER_FOLLOWARE_FAIL'


// user following... 
export const ADD_USER_FOLLOWING_LOADING = 'ADD_USER_FOLLOWING_LOADING'
export const ADD_USER_FOLLOWING_SUCCESS = 'ADD_USER_FOLLOWING_SUCCESS'
export const ADD_USER_FOLLOWING_FAIL = 'ADD_USER_FOLLOWING_FAIL'


// click follow...
export const ADD_FOLLOWUSER_LOADING = 'ADD_FOLLOWUSER_LOADING'
export const ADD_FOLLOWUSER_SUCCESS = 'ADD_FOLLOWUSER_SUCCESS'
export const ADD_FOLLOWUSER_FAIL = 'ADD_FOLLOWUSER_FAIL'


// user story image.. 
export const ADD_USER_STORY_LOADING = 'ADD_USER_STORY_LOADING'
export const ADD_USER_STORY_SUCCESS = 'ADD_USER_STORY_SUCCESS'
export const ADD_USER_STORY_FAIL = 'ADD_USER_STORY_FAIL'

// list users...
export const ADD_LIST_USERS_FAIL = 'ADD_LIST_USERS_FAIL'
export const ADD_LIST_USERS_LOADING = 'ADD_LIST_USERS_LOADING'
export const ADD_LIST_USERS_SUCCESS = 'ADD_LIST_USERS_SUCCESS'






// create post ===>
export const ADD_USER_POST_LOADING = 'ADD_USER_POST_LOADING'
export const ADD_USER_POST_SUCCESS = 'ADD_USER_POST_SUCCESS'
export const ADD_USER_POST_FAIL = 'ADD_USER_POST_FAIL'


// post only User... 
export const ADD_POST_PRIVATE_LOADING = 'ADD_POST_PRIVATE_LOADING'
export const ADD_POST_PRIVATE_SUCESS = 'ADD_POST_PRIVATE_SUCESS'
export const ADD_POST_PRIVATE_FAIL = 'ADD_POST_PRIVATE_FAIL'


// viws post all 
export const ADD_POST_VIWES_LOADING = 'ADD_POST_VIWES_LOADING'
export const ADD_POST_VIWES_SUCCESS = 'ADD_POST_VIWES_SUCCESS'
export const ADD_POST_VIWES_FAILT = 'ADD_POST_VIWES_FAILT'


// delete post from user..
export const ADD_DELETE_USER_SUCCESS = 'ADD_DELETE_USER_SUCCESS'
export const ADD_DELETE_USER_FAIL = 'ADD_DELETE_USER_FAIL'

// views like 
export const ADD_LIKE_POST_SUCCESS= 'ADD_LIKE_POST_SUCCESS'
export const ADD_LIKE_POST_FAIL = 'ADD_LIKE_POST_FAIL'


// add like to post 
export const ADD_LIKE_USER_SUCCESSS = 'ADD_LIKE_USER_SUCCESSS'
export const ADD_LIKE_USER_FAIL = 'ADD_LIKE_USER_FAIL'


// add comment .. 
export const ADD_USER_COMMENT_LOADING = 'ADD_USER_COMMENT_LOADING'
export const ADD_USER_COMMENT_SUCCESS = 'ADD_USER_COMMENT_SUCCESS'
export const ADD_USER_COMMENT_FAIL = 'ADD_USER_COMMENT_FAIL'
// add like to comment.. 
export const ADD_LIKE_COMMENT_SUCCESS = 'ADD_LIKE_COMMENT_SUCCESS'
export const ADD_LIKE_COMMENT_FAIL = 'ADD_LIKE_COMMENT_FAIL'